// This file is auto-generated by TanStack Router
// It is recommended to generate this file using the TanStack Router CLI
// For now, we'll create it manually

import { Route as rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as LoginRoute } from './routes/login';
import { Route as RegisterRoute } from './routes/register';
import { Route as DashboardRoute } from './routes/dashboard';

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      preLoaderRoute: typeof LoginRoute;
      parentRoute: typeof rootRoute;
    };
    '/register': {
      preLoaderRoute: typeof RegisterRoute;
      parentRoute: typeof rootRoute;
    };
    '/dashboard': {
      preLoaderRoute: typeof DashboardRoute;
      parentRoute: typeof rootRoute;
    };
  }
}

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  RegisterRoute,
  DashboardRoute,
]);
